### ISSUE TITLE
[Image Preproc] Packing into a module

### ISSUE THREAD

**Issue by Nana2929** [Nana2929/Medical-VQA#8]
Main Contributor: @zhiao777774

**Comment by Nana2929** [comment]
## TODO

- [x]  filter images: Some images under the same mod_organ may go thru preproc, some may not be preprocessed. Define this gate. 
- [x]  Integrate @00757033  X-ray preproc
- [x]  Integrate ABD_CT preproc
